#cloud-config
package_upgrade: true
packages:
  - curl
  - git
  - install
  - ca-certificates
  - gnupg
  - lsb-release
runcmd:
  # Installing kubectl
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - chmod +x kubectl
  - mkdir -p ~/.local/bin/kubectl
  - mv ./kubectl ~/.local/bin/kubectl

  # Installing azure cli
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

  # Installing helm
  - curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https --yes
  - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  - sudo apt-get update
  - sudo apt-get install helm

  # Installing docker
  - sudo apt-get install docker.io --yes

  # Install Github Self-Runner
  # - export RUNNER_CFG_PAT=__runnerPAT__
  # - curl -s https://raw.githubusercontent.com/actions/runner/main/scripts/create-latest-svc.sh | bash -s __githubRepo__