name: dev-sec
on: 
  workflow_dispatch:
env:
  DOTNET_VERSION: 6.0.x
  USE_DOTNET_PREVIEW: true
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: ${{ env.USE_DOTNET_PREVIEW }}
      - name: Restore all projects
        run: |
          dotnet restore eShopOnDapr.sln  
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif snyk test --file=eShopOnDapr.sln
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
