name: hello-world

on:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: self-hosted
    
    env:
      WEBAPP_PATH: src/HelloWorlExpress
      
    steps:

      - uses: actions/checkout@v2

      # - uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      #           sudo docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/hello-world:${{ github.sha }}    

      - run: |
          pushd './${{ env.WEBAPP_PATH }}'
          sudo az acr login -n ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          sudo docker build . -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/hello-world:${{ github.sha }}               
